### ISSUE TITLE
Tag name in API needs to be updated

### ISSUE THREAD

**Issue by marcodarko** [UTHealth-CCB/DataCommons#2]
Hi We noticed that the API you registered with SmartAPI.info has tag called "NIHDatacommons" and it should be "NIHdatacommons" no capital "D".  Nothing major, it just causes a double tag UI bug on the app.  Thank you so much, hope it's not too much of an inconvenience. 

After you change it you can refresh it manually via our dashboard at smartapi.info

Thank you!

**Comment by ftiryaki** [comment]
Hi, thank you for your feedback @marcodarko . It's fixed to NIHdatacommons.
